mkdir linux

export CFLAGS="-Ofast -flto -fwhole-program -Wno-unused-result"

export GLOBOBJS=""

export GLOBOBJS+=" am_map.c"
export GLOBOBJS+=" doomdef.c"
export GLOBOBJS+=" doomstat.c"
export GLOBOBJS+=" dstrings.c"
export GLOBOBJS+=" d_items.c"
export GLOBOBJS+=" d_main.c"
export GLOBOBJS+=" d_net.c"
export GLOBOBJS+=" f_finale.c"
export GLOBOBJS+=" f_wipe.c"
export GLOBOBJS+=" g_game.c"
export GLOBOBJS+=" hu_lib.c"
export GLOBOBJS+=" hu_stuff.c"
export GLOBOBJS+=" info.c"
export GLOBOBJS+=" i_lib.c"
export GLOBOBJS+=" m_argv.c"
export GLOBOBJS+=" m_bbox.c"
export GLOBOBJS+=" m_cheat.c"
export GLOBOBJS+=" m_fixed.c"
export GLOBOBJS+=" m_menu.c"
export GLOBOBJS+=" m_misc.c"
export GLOBOBJS+=" m_random.c"
export GLOBOBJS+=" m_swap.c"
export GLOBOBJS+=" memio.c"
export GLOBOBJS+=" mus2mid.c"
export GLOBOBJS+=" p_ceilng.c"
export GLOBOBJS+=" p_doors.c"
export GLOBOBJS+=" p_enemy.c"
export GLOBOBJS+=" p_floor.c"
export GLOBOBJS+=" p_inter.c"
export GLOBOBJS+=" p_lights.c"
export GLOBOBJS+=" p_map.c"
export GLOBOBJS+=" p_maputl.c"
export GLOBOBJS+=" p_mobj.c"
export GLOBOBJS+=" p_plats.c"
export GLOBOBJS+=" p_pspr.c"
export GLOBOBJS+=" p_saveg.c"
export GLOBOBJS+=" p_setup.c"
export GLOBOBJS+=" p_sight.c"
export GLOBOBJS+=" p_spec.c"
export GLOBOBJS+=" p_switch.c"
export GLOBOBJS+=" p_telept.c"
export GLOBOBJS+=" p_tick.c"
export GLOBOBJS+=" p_user.c"
export GLOBOBJS+=" r_bsp.c"
export GLOBOBJS+=" r_data.c"
export GLOBOBJS+=" r_draw.c"
export GLOBOBJS+=" r_main.c"
export GLOBOBJS+=" r_plane.c"
export GLOBOBJS+=" r_segs.c"
export GLOBOBJS+=" r_sky.c"
export GLOBOBJS+=" r_things.c"
export GLOBOBJS+=" sounds.c"
export GLOBOBJS+=" st_lib.c"
export GLOBOBJS+=" st_stuff.c"
export GLOBOBJS+=" s_sound.c"
export GLOBOBJS+=" tables.c"
export GLOBOBJS+=" v_video.c"
export GLOBOBJS+=" wi_stuff.c"
export GLOBOBJS+=" w_wad.c"
export GLOBOBJS+=" z_zone.c"

gcc $GLOBOBJS $CFLAGS -shared -fPIC -fvisibility=hidden -DDllExport="__attribute__((visibility(\"default\"))) __attribute__((externally_visible))" -o linux/libdoom.so
